export class PrayerConstants {

  public static readonly firstPrayer = 'Dear Lord,<br>I admit that I am powerless over my addiction.<br>I admit that my life is unmanageable when I try to control it.<br>Help me this day to understand<br>The true meaning of powerlessness.<br>Remove from me all denial of my addiction.';
  public static readonly secondPrayer = 'Heavenly Father,<br>I know in my heart that only you can restore me to sanity.<br>I humbly ask that you remove all twisted thought &<br>Addictive behavior from me this day.<br>Heal my spirit & restore in me a clear mind.';
  public static readonly thirdPrayer = 'God,<br>I offer myself to Thee.<br>To build with me & to do with me as Thou wilt.<br>Relieve me of the bondage of self, that I may better do Thy will.<br>Take away my difficulties,<br>That victory over them may bear witness.<br>To those I would help of Thy Power,<br>Thy love & Thy way of life,<br>May I do Thy will always!';
  public static readonly fourthPrayer = 'Dear God,<br>It is I who has made my life a mess.<br>I have done it, but I cannot undo it.<br>My mistakes are mine &<br>I will begin a searching & fearless moral inventory.<br>I will write down my wrongs<br>But I will also include that which is good.<br>I pray for the strength to complete the task.';
  public static readonly fifthPrayer = 'Higher Power,<br>My inventory has shown me who I am,<br>Yet I ask for Your help<br>In admitting my wrongs to another person & to You.<br>Assure me, & be with me, in this Step,<br>For without this Step I cannot progress in my recovery.<br>With Your help, I can do this, & I do it.';
  public static readonly sixthPrayer = 'Dear God,<br>I am ready for Your help<br>In removing from me the defects of character<br>Which I now realize are an obstacle to my recovery.<br>Help me to continue being honest with myself &<br>Guide me toward spiritual & mental health.';
  public static readonly seventhPrayer = 'My Creator,<br>I am now willing that you should have all of me, good & bad.<br>I pray that you now remove from me every single defect of character<br>Which stands in the way of my usefulness to you & my fellows.<br>Grant me strength, as I go out from here to do your bidding.';
  public static readonly eighthPrayer = 'Higher Power,<br>I ask Your help in making my list of all those I have harmed.<br>I will take responsibility for my mistakes &<br>Be forgiving to others as You are forgiving to me.<br>Grant me the willingness to begin my restitution.<br>This I pray.';
  public static readonly ninethPrayer = 'Higher Power,<br>I pray for the right attitude to make my amends,<br>Being ever mindful not to harm others in the process.<br>I ask for Your guidance in making indirect amends.<br>Most important, I will continue to make amends<br>By staying abstinent, helping others &<br>Growing in spiritual progress.';
  public static readonly tenthPrayer = 'I pray I may continue:<br>To grow in understanding & effectiveness;<br>To take daily spot check inventories of myself;<br>To correct mistakes when I make them;<br>To take responsibility for my actions;<br>To be ever aware of my negative &<br>Self-defeating attitudes & behaviors;<br>To keep my willfulness in check;<br>To always remember I need Your help;<br>To keep love & tolerance of others as my code; &<br>To continue in daily prayer how I can best serve You,<br>My Higher Power.';
  public static readonly eleventhPrayer = 'Higher Power, as I understand You,<br>I pray to keep my connection with You<br>Open & clear from the confusion of daily life.<br>Through my prayers & meditation I ask especially for<br>Freedom from self-will, rationalization, & wishful thinking.<br>I pray for the guidance of correct thought & positive action.<br>Your will Higher Power, not mine, be done.';
  public static readonly twelvethPrayer = 'Dear God,<br>My spiritual awakening continues to unfold.<br>The help I have received I shall pass on & give to others,<br>Both in & out of the Fellowship.<br>For this opportunity I am grateful.<br>I pray most humbly to continue walking day by day<br>On the road of spiritual progress.<br>I pray for the inner strength & wisdom<br>To practice the principles of this way of life in all I do & say.<br>I need You, my friends, & the program every hour of every day.<br>This is a better way to live.';

  public static readonly serenityPrayer = 'God,<br>Grant me the serenity to accept the things I cannot change,<br>The courage to change the things I can,<br>And wisdom to know the difference.';
  public static readonly lordsPrayer = 'Our Father,<br>Who art in heaven, hallowed be thy name.<br>Thy Kingdom come, thy will be done, on earth as it is in heaven.<br>Give us this day our daily bread.<br>And forgive us our trespasses, as we forgive those who trespass against us.<br>And lead us not into temptation, but deliver us from evil.<br>For thine is the kingdom, the power and the glory, forever and ever';
  public static readonly stFrancisPrayer = 'Lord,<br>Make me a channel of thy peace, that where there is hatred, I may bring love;<br>That where there is wrong, I may bring the spirit of forgiveness;<br>That where there is discoid, I may bring harmony;<br>That where there is error, I may bring truth;<br>That where there is doubt, I may bring faith;<br>That where there is despair, I may bring hope;<br>That where there are shadows, I may bring light;<br>That where there is sadness, I may bring joy.<br>Lord,<br>Trant that I may seek rather to comfort than to be comforted;<br>To understand, than to be understood;<br>To love, than to be loved.<br>For it is by self-forgetting that one finds. It is by forgiving that one is forgiven.<br>It is by dying that one awakens to Eternal Life.';
  public static readonly morningPrayer = 'God,<br>direct my thinking today so that it is divorced of self-pity, dishonesty, self-will, self-seeking and fear.<br>God inspire my thinking, decisions and intuitions.<br>Help me to relax and take it easy. Free me from doubt and indecision.<br>Guide me through this day and show me my next step.<br>God, give me what I need to take care of any problems.<br>I ask all these things that I may be of maximum service to you and my fellow man (in the name of the Steps I pray.)';
  public static readonly nightPrayer = 'God,<br>forgive me where I have been resentful, selfish, dishonest or afraid today.<br>Help me to not keep anything to myself but to discuss it all openly with another person<br>show me where I owe an apology and help me make it.<br>Help me to be kind and loving to all people. Use me in the mainstream of life God.<br>Remove worry, remorse or morbid (sick) reflections that I may be of usefulness to others.';
  public static readonly greatSpiritPrayer = 'Oh, Great Spirit,<br>Whose voice I hear in the wind, whose breath gives life to all the world.<br>Hear me; I need your strength and wisdom.<br>Let me walk in beauty, and make my eyes ever behold the red and purple sunset.<br>Make my hands respect the things you have made and my ears sharp to hear your voice.<br>Make me wise so that I may understand the things you have taught my people.<br>Help me to remain calm and strong in the face of all that comes towards me.<br>Let me learn the lessons you have hidden in every leaf and rock.<br>Help me seek pure thoughts and act with the intention of helping others.<br>Help me find compassion without empathy overwhelming me.<br>I seek strength, not to be greater than my brother, but to fight my greatest enemy, Myself.<br>Make me always ready to come to you with clean hands and straight eyes.<br>So when life fades, as the fading sunset, my spirit may come to you without shame.';
}
